services:
  - type: web
    name: cryptochart-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_MODE
        value: supabase
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_KEY
        fromSecret: SUPABASE_KEY
